version: 0.0
os: linux
files:
  - source: target/ROOT.war
    destination: /var/lib/tomcat9/webapps
file_exists_behavior: OVERWRITE
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
